package victor.kryz.hr.sb.domain;
// Generated Dec 7, 2016 12:59:58 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
//import javax.validation.constraints.Size;

/**
 * Regions generated by hbm2java
 */
@Entity
@Table(name="REGIONS")
public class Region  implements java.io.Serializable {

	@Id 
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="REGION_ID", precision=22, scale=0)
	private BigDecimal regionId;
	
	
	@Column(name = "REGION_NAME")
//	@Size(max = 25)
    private String regionName;
	
//	@OneToMany
//	@JoinColumn(name = "REGION_ID")
//    private Set<Country> countries = new HashSet<Country>(0);

    public Region() {
    }
	
    public Region(BigDecimal regionId) {
        this.regionId = regionId;
    }
    
    public Region(BigDecimal regionId, String regionName) {
        this.regionId = regionId;
        this.regionName = regionName;
     }
    
    
//    public Region(BigDecimal regionId, String regionName, Set<Country> countrieses) {
//       this(regionId, regionName);	
////       this.countries = countrieses;
//    }
   
    public BigDecimal getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(BigDecimal regionId) {
        this.regionId = regionId;
    }
    public String getRegionName() {
        return this.regionName;
    }
    
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }
//    public Set<Country> getCountries() {
//        return this.countries;
//    }
    
//    public void setCountrieses(Set<Country> countrieses) {
//        this.countries = countrieses;
//    }
}


